name: finapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  pocketbase: ^0.18.1
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.3.2
  record: ^5.1.2
  path_provider: ^2.1.4
  http: ^1.2.2
  http_parser: ^4.0.2
  dio: ^5.7.0
  get_it: ^8.0.1
  url_launcher: ^6.3.1
  graphic: ^2.5.0
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  skeletonizer: ^1.4.2
  package_info_plus: ^8.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/gen/
  line_length: 80

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/icon/icon.png
